#!/usr/bin/env python3
"""Write the shared site chrome (nav with mobile menu, footer, dark theme)
into every public marketing page, between marker comments.

The site has no build step, so this is the single source of truth for the
parts every page shares. Edit NAV/FOOTER/CSS here, run it, commit the
pages it rewrote, then deploy (infra/landing-worker/deploy.sh). Running it
twice changes nothing.

    python3 infra/scripts/sync-site-chrome.py
"""
import os
import re
import sys

PUBLIC = os.path.join(os.path.dirname(__file__), "..", "..", "src", "api-gateway-rs", "public")
# page file -> its URL path (for aria-current)
PAGES = {
    "landing.html": "/", "about.html": "/about", "docs.html": "/docs", "guide.html": "/guide",
    "status.html": "/status", "webhook-audit.html": "/webhook-audit", "vs-temporal.html": "/vs-temporal",
    "vs-composio.html": "/vs-composio", "vs-arcade.html": "/vs-arcade", "postmortem-2026-09.html": "/postmortem-2026-09",
    # templates pages.rs fills at request time: chrome only, no canonical/share tags
    "doc-template.html": None, "404.html": None,
}
# pages still built on the old light-theme variables: get the dark theme layer
THEMED = {"about.html", "docs.html", "guide.html", "status.html", "webhook-audit.html", "vs-temporal.html", "vs-composio.html", "vs-arcade.html"}

FONTS = '<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600&display=swap" rel="stylesheet">'
MARK = ('<span class="sn-mark"><svg width="18" height="18" viewBox="0 0 24 24" fill="none">'
        '<circle cx="8.5" cy="12" r="5.6" fill="none" stroke="#ECEFF3" stroke-width="2"/>'
        '<circle cx="15.5" cy="12" r="5.6" fill="#F2B544"/></svg></span>')
GITHUB = ('<svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 2C6.48 2 2 6.58 2 12.25c0 4.53 2.87 8.37 6.84 9.73.5.1.68-.22.68-.5 0-.24-.01-.87-.01-1.71-2.78.62-3.37-1.37-3.37-1.37-.46-1.2-1.11-1.52-1.11-1.52-.91-.64.07-.62.07-.62 1 .07 1.53 1.05 1.53 1.05.89 1.56 2.34 1.11 2.91.85.09-.66.35-1.11.63-1.37-2.22-.26-4.56-1.14-4.56-5.06 0-1.12.39-2.03 1.03-2.75-.1-.26-.45-1.31.1-2.72 0 0 .84-.28 2.75 1.05a9.3 9.3 0 0 1 2.5-.35c.85 0 1.71.12 2.5.35 1.91-1.33 2.75-1.05 2.75-1.05.55 1.41.2 2.46.1 2.72.64.72 1.03 1.63 1.03 2.75 0 3.93-2.34 4.79-4.57 5.05.36.32.68.95.68 1.92 0 1.39-.01 2.51-.01 2.85 0 .28.18.61.69.5A10.26 10.26 0 0 0 22 12.25C22 6.58 17.52 2 12 2Z"/></svg>')
REPO = "https://github.com/sumedhchatse/agentraas"
LINKS = [("Platform", "/#features"), ("Open source", "/#open-source"), ("Pricing", "/#pricing"),
         ("Docs", "/docs"), ("Guide", "/guide"), ("Status", "/status")]


def nav(path):
    def a(label, href):
        cur = ' aria-current="page"' if href == path else ""
        return f'<a href="{href}"{cur}>{label}</a>'
    links = "".join(a(l, h) for l, h in LINKS)
    return f'''<!-- site-nav:start (generated by infra/scripts/sync-site-chrome.py; edit there) -->
<header class="sn">
  <div class="sn-in">
    <a href="/" class="sn-brand" aria-label="AgentRaaS home">{MARK}AgentRaaS</a>
    <nav class="sn-links" aria-label="Main">{links}</nav>
    <div class="sn-right">
      <a href="{REPO}" target="_blank" rel="noopener" class="sn-gh" aria-label="AgentRaaS on GitHub">{GITHUB}</a>
      <a href="/dashboard" class="sn-btn s">Log in</a>
      <a href="/dashboard" class="sn-btn p" data-gtm-event="cta_click" data-gtm-label="nav_get_started">Get started</a>
      <button class="sn-menu" type="button" aria-label="Menu" aria-expanded="false" aria-controls="sn-panel"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg></button>
    </div>
  </div>
  <nav class="sn-panel" id="sn-panel" aria-label="Main">{links}<a href="{REPO}" target="_blank" rel="noopener">GitHub</a><a href="/dashboard">Log in</a></nav>
</header>
<script>
(function () {{
  var nav = document.currentScript.previousElementSibling, btn = nav.querySelector('.sn-menu');
  btn.addEventListener('click', function () {{
    var open = !nav.hasAttribute('data-open');
    if (open) nav.setAttribute('data-open', ''); else nav.removeAttribute('data-open');
    btn.setAttribute('aria-expanded', String(open));
  }});
  nav.querySelectorAll('.sn-panel a').forEach(function (a) {{
    a.addEventListener('click', function () {{ nav.removeAttribute('data-open'); btn.setAttribute('aria-expanded', 'false'); }});
  }});
}})();
</script>
<!-- site-nav:end -->'''


COPY_JS = r'''<script>
(function () {
  // Copy button on code blocks (docs, guides); the homepage's terminal demos are skipped.
  if (!navigator.clipboard) return;
  document.querySelectorAll('pre').forEach(function (pre) {
    if (pre.closest('.terminal') || pre.querySelector('.pre-copy')) return;
    pre.classList.add('has-copy');
    var b = document.createElement('button');
    b.type = 'button'; b.className = 'pre-copy'; b.textContent = 'Copy';
    b.addEventListener('click', function () {
      navigator.clipboard.writeText(pre.innerText.replace(/\s*Cop(y|ied)$/, '')).then(function () {
        b.textContent = 'Copied'; setTimeout(function () { b.textContent = 'Copy'; }, 1400);
      });
    });
    pre.appendChild(b);
  });
})();
</script>
'''

FOOTER = f'''<!-- site-footer:start (generated by infra/scripts/sync-site-chrome.py; edit there) -->
<footer class="sf">
  <div class="sf-in">
    <div class="sf-grid">
      <div class="sf-brand">
        <a href="/" class="sn-brand">{MARK}AgentRaaS</a>
        <p>Stops AI agents from running the same API call twice, holds risky calls for human approval, and records every action.</p>
        <a href="{REPO}" target="_blank" rel="noopener" class="sn-btn s">{GITHUB}&nbsp;Star on GitHub</a>
      </div>
      <div class="sf-col"><h4>Product</h4><a href="/#features">Platform</a><a href="/#open-source">Open source</a><a href="/#pricing">Pricing</a><a href="/dashboard">Dashboard</a><a href="/status">Status</a><a href="/postmortem-2026-09">Postmortems</a></div>
      <div class="sf-col"><h4>Docs</h4><a href="/guide">Getting started</a><a href="/docs">Documentation</a><a href="/webhook-audit">Free webhook audit</a><a href="{REPO}" target="_blank" rel="noopener">GitHub</a></div>
      <div class="sf-col"><h4>Compare</h4><a href="/vs-temporal">vs Temporal</a><a href="/vs-composio">vs Composio</a><a href="/vs-arcade">vs Arcade.dev</a></div>
      <div class="sf-col"><h4>Legal</h4><a href="/license">License</a><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="/security">Security</a></div>
      <div class="sf-col"><h4>Company</h4><a href="/about">About</a><a href="mailto:hello@agentraas.io">hello@agentraas.io</a></div>
    </div>
    <div class="sf-bottom"><span>&copy; 2026 AgentRaaS</span><span>Built with Rust, Redis, PostgreSQL, Podman, and the fear of double-charging a customer at 2 AM.</span></div>
  </div>
</footer>
''' + COPY_JS + '''<!-- site-footer:end -->'''

CHROME_CSS = '''  /* site-chrome:start (generated by infra/scripts/sync-site-chrome.py; edit there) */
  .sn { position: sticky; top: 0; z-index: 60; background: rgba(8,9,11,0.92); -webkit-backdrop-filter: blur(10px); backdrop-filter: blur(10px); border-bottom: 1px solid #22272E; font-family: Inter, system-ui, sans-serif; }
  .sn-in, .sf-in { max-width: 1200px; margin: 0 auto; padding: 0 28px; }
  .sn-in { height: 64px; display: flex; align-items: center; justify-content: space-between; gap: 20px; }
  .sn-brand { display: flex; align-items: center; gap: 10px; color: #ECEFF3; text-decoration: none; font: 700 17px Inter, system-ui, sans-serif; letter-spacing: -0.01em; }
  .sn-brand:hover { text-decoration: none; }
  .sn-mark { width: 30px; height: 30px; border-radius: 7px; display: grid; place-items: center; flex-shrink: 0; background: linear-gradient(180deg, #1D2127, #121418); box-shadow: inset 0 0 0 1px #2E343C, inset 0 1px 0 rgba(255,255,255,0.06); }
  .sn-links { display: flex; gap: 26px; }
  .sn-links a { color: #9AA3AD; font-size: 14px; font-weight: 500; text-decoration: none; transition: color 0.15s ease; }
  .sn-links a:hover, .sn-links a[aria-current] { color: #ECEFF3; text-decoration: none; }
  .sn-right { display: flex; align-items: center; gap: 12px; }
  .sn-gh { display: flex; color: #9AA3AD; } .sn-gh:hover { color: #ECEFF3; }
  .sn-btn { display: inline-flex; align-items: center; gap: 6px; padding: 8px 14px; border-radius: 6px; font: 600 14px Inter, system-ui, sans-serif; text-decoration: none; border: 1px solid transparent; white-space: nowrap; transition: background 0.18s ease, border-color 0.18s ease, transform 0.18s ease; }
  .sn-btn:hover { text-decoration: none; transform: translateY(-1px); }
  .sn-btn.p { background: #F2B544; color: #1A1206; } .sn-btn.p:hover { background: #F5C262; }
  .sn-btn.s { background: #111418; border-color: #2F353D; color: #ECEFF3; } .sn-btn.s:hover { border-color: #444B54; }
  .sn-btn svg { width: 16px; height: 16px; }
  .sn-menu { display: none; width: 40px; height: 36px; place-items: center; background: #111418; border: 1px solid #2F353D; border-radius: 6px; color: #ECEFF3; cursor: pointer; }
  .sn-panel { display: none; }
  .sf { margin-top: 96px; padding: 64px 0 36px; border-top: 1px solid #22272E; background: #08090B; color: #ECEFF3; font-family: Inter, system-ui, sans-serif; }
  .sf-grid { display: grid; grid-template-columns: 1.6fr repeat(5, 1fr); gap: 32px; margin-bottom: 48px; }
  .sf-brand p { color: #9AA3AD; font-size: 14px; line-height: 1.6; margin: 14px 0 18px; max-width: 280px; }
  .sf-col h4 { font: 600 13px Inter, system-ui, sans-serif; color: #ECEFF3; margin: 0 0 14px; letter-spacing: 0; }
  .sf-col a { display: block; color: #9AA3AD; font-size: 14px; margin-bottom: 10px; text-decoration: none; }
  .sf-col a:hover { color: #ECEFF3; }
  .sf-bottom { display: flex; justify-content: space-between; gap: 20px; flex-wrap: wrap; color: #6B737C; font-size: 13px; padding-top: 24px; border-top: 1px solid #22272E; }
  pre.has-copy { position: relative; }
  .pre-copy { position: absolute; top: 8px; right: 8px; font: 600 12px Inter, system-ui, sans-serif; color: #ECEFF3; background: #1A1E24; border: 1px solid #2F353D; border-radius: 5px; padding: 4px 10px; cursor: pointer; opacity: 0.75; }
  .pre-copy:hover, .pre-copy:focus-visible { opacity: 1; border-color: #444B54; }
  .sn a:focus-visible, .sn button:focus-visible, .sf a:focus-visible { outline: 2px solid #F2B544; outline-offset: 3px; border-radius: 4px; }
  @media (max-width: 1080px) {
    .sn-links, .sn-right .sn-gh, .sn-right .sn-btn.s { display: none; }
    .sn-menu { display: grid; }
    .sn[data-open] .sn-panel { display: block; }
    .sn-panel { border-top: 1px solid #22272E; padding: 6px 28px 16px; }
    .sn-panel a { display: block; padding: 12px 0; color: #ECEFF3; font-size: 16px; text-decoration: none; border-bottom: 1px solid #16191E; }
    .sn-panel a:last-child { border-bottom: 0; }
    .sn-panel a[aria-current] { color: #F2B544; }
    .sf-grid { grid-template-columns: repeat(3, 1fr); }
    .sf-brand { grid-column: 1 / -1; }
  }
  @media (max-width: 680px) {
    .sn-in, .sf-in { padding: 0 16px; }
    .sn-panel { padding: 4px 16px 14px; }
    .sn-btn.p { padding: 8px 12px; }
    .sf-grid { grid-template-columns: 1fr 1fr; }
  }
  /* site-chrome:end */
'''

THEME_CSS = '''  /* site-theme:start (generated by infra/scripts/sync-site-chrome.py; edit there)
     Repoints the page's own light-theme variables at the site's dark palette. */
  :root {
    color-scheme: dark;
    --ink: #08090B; --ink-2: #111418; --ink-3: #161A1F; --panel: #111418; --paper: #0D0F12; --paper-panel: #111418;
    --border-dark: #22272E; --border-light: #22272E; --text: #ECEFF3; --text-dark: #ECEFF3; --muted: #9AA3AD; --muted-dark: #9AA3AD;
    --signal: #F2B544; --signal-deep: #1A1206; --claim: #4CC38A; --alert: #F0645A; --dedup: #F2C66D; --warn: #F2B544; --info: #7CB8E0;
  }
  body { background: #08090B; color: #ECEFF3; font-family: Inter, system-ui, sans-serif; -webkit-font-smoothing: antialiased; }
  h1, h2, h3, h4 { font-family: Inter, system-ui, sans-serif; letter-spacing: -0.02em; }
  h1 { letter-spacing: -0.035em; }
  code, pre, kbd, .mono { font-family: 'JetBrains Mono', ui-monospace, monospace; }
  /* site-theme:end */
'''


SITE = "https://agentraas.io"


def head_meta(s, path):
    """One consistent, absolute set of canonical + share tags per page."""
    title = re.search(r"<title>([^<]*)</title>", s).group(1)
    desc_m = re.search(r'<meta name="description" content="([^"]*)"', s)
    desc = desc_m.group(1) if desc_m else title
    s = re.sub(r'\n?<link rel="canonical"[^>]*>', "", s)
    s = re.sub(r'\n?<meta (?:property|name)="(?:og:type|og:site_name|og:url|og:image|og:image:width|og:image:height|twitter:card|twitter:image)"[^>]*>', "", s)
    s = re.sub(r"\n?<!-- site-meta:start.*?site-meta:end -->", "", s, flags=re.S)
    has_og_title = 'property="og:title"' in s
    has_og_desc = 'property="og:description"' in s
    has_tw_title = 'name="twitter:title"' in s
    tags = [f'<link rel="canonical" href="{SITE}{path}">',
            '<meta property="og:type" content="website">', '<meta property="og:site_name" content="AgentRaaS">',
            f'<meta property="og:url" content="{SITE}{path}">',
            f'<meta property="og:image" content="{SITE}/og-image.png">',
            '<meta property="og:image:width" content="1200">', '<meta property="og:image:height" content="630">',
            '<meta name="twitter:card" content="summary_large_image">',
            f'<meta name="twitter:image" content="{SITE}/og-image.png">']
    if not has_og_title: tags.append(f'<meta property="og:title" content="{title}">')
    if not has_og_desc: tags.append(f'<meta property="og:description" content="{desc}">')
    if not has_tw_title: tags.append(f'<meta name="twitter:title" content="{title}">')
    block = "<!-- site-meta:start (generated by infra/scripts/sync-site-chrome.py) -->\n" + "\n".join(tags) + "\n<!-- site-meta:end -->"
    return s.replace("</title>", "</title>\n" + block, 1)


def put_block(s, start, end, block, fallback):
    pat = re.compile(re.escape(start) + r".*?" + re.escape(end), re.S)
    if pat.search(s):
        return pat.sub(lambda m: block, s, count=1)
    return fallback(s, block)


def main():
    changed = []
    for name, path in PAGES.items():
        p = os.path.join(PUBLIC, name)
        s = o = open(p).read()
        s = re.sub(r'<link href="https://fonts\.googleapis\.com/css2\?[^"]*" rel="stylesheet">', FONTS, s, count=1)
        if path is not None:
            s = head_meta(s, path)
        css = CHROME_CSS + (THEME_CSS if name in THEMED else "")
        css = css.replace("  /* site-theme:start", "  /* site-theme:start")
        s = re.sub(r"  /\* site-chrome:start.*?/\* site-chrome:end \*/\n", "", s, flags=re.S)
        s = re.sub(r"  /\* site-theme:start.*?/\* site-theme:end \*/\n", "", s, flags=re.S)
        s = s.replace("</style>", css + "</style>", 1)
        # nav: replace marker block, else the page's first <header ...>...</header>
        def first_header(t, block):
            t2, n = re.subn(r"<header\b[^>]*>.*?</header>", lambda m: block, t, count=1, flags=re.S)
            assert n == 1, f"{name}: no <header> to replace"
            return t2
        s = put_block(s, "<!-- site-nav:start", "<!-- site-nav:end -->", nav(path), first_header)
        # footer: replace marker block, else the page's last <footer>...</footer>, else before </body>
        def last_footer(t, block):
            ms = list(re.finditer(r"<footer\b[^>]*>.*?</footer>", t, re.S))
            if ms:
                m = ms[-1]
                return t[:m.start()] + block + t[m.end():]
            return t.replace("</body>", block + "\n</body>", 1)
        s = put_block(s, "<!-- site-footer:start", "<!-- site-footer:end -->", FOOTER, last_footer)
        if s != o:
            open(p, "w").write(s)
            changed.append(name)
    print("updated:", ", ".join(changed) if changed else "nothing (already in sync)")


if __name__ == "__main__":
    sys.exit(main())
